# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcf23b89b8d31f7251e12cb7d617427043350855286a3d515c04cd74017ff825cfe85d435a2905de785a1c6879b14e7ed3027ecfe30fd0974a7c3be63e15e88e

test:
  secret_key_base: d3eb376495788fabf9c449d1cddf79455233790332c629d65d24b8e2ad213bef220fb340ecc7e8226623f500184c72e4092b6986fc42ae66bf5e0da2b39741fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
